[package]
name = "borat"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.75"
colored = "2.0.4"
console = "0.15.7"
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
